version: '2.1'
services:

  eurekaserver:
    image: maxb/laf-eurekasvr:vk-laf-eurekasvr
    ports:
       - "8761:8761"


  configserver:
    image: maxb/laf-confsvr:vk-laf-confsvr
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"


  zuulserver:
    image: maxb/laf-zuulsvr:vk-laf-zuulsvr
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: httpd.access
#    depends_on:
#      - fluentd

#  auth-server:
#    image:  maxb/laf-auth-service:vk-laf-auth-service
#    container_name: auth-server
#    ports:
#      - "8901:8901"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "8901"
#      CONFIGSERVER_PORT: 8888
#      EUREKASERVER_PORT: 8761
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
##    logging:
##      driver: "fluentd"
##      options:
##        fluentd-address: localhost:24224
##        tag: httpd.access
##    depends_on:
##      - fluentd
#
#  database-auth:
#    image: mongo
#    container_name: auth-mongo
#    volumes:
#      - $HOME/auth-data:/data/db
#      - $HOME/auth-datacd:/data/bkp
#    restart: always





  likeservice:
    image: maxb/laf-like-service:vk-laf-like-service
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:
      - fluentd

  database-like:
    image: mongo
#    container_name: like-mongo
    volumes:
      - $HOME/like-data:/data/db
      - $HOME/like-datacd:/data/bkp
    restart: always


  followeservice:
    image: maxb/laf-follower-service:vk-laf-follower-service
    ports:
      - "8086:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8086"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:
      - fluentd

  database-follower:
    image: mongo
    volumes:
      - $HOME/follower-data:/data/db
      - $HOME/follower-datacd:/data/bkp
    restart: always

  userservice:
    image: maxb/laf-user-service:vk-laf-user-service
    ports:
      - "8087:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:
      - fluentd

  database-user:
    image: mongo
#    ports:  # for demo/debug purpose only
#      - 27017:27017
    volumes:
      - $HOME/user-data:/data/db
      - $HOME/user-datacd:/data/bkp
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: maxb/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "changeme"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    expose:
      - 9200


  fluentd:
    container_name: fluentd
    image: maxb/fluentd:latest
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"

  kibana:
    container_name: kibana
    image: maxb/kibana:latest
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch




  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092