spring:
  cloud:
    stream:
      bindings:

        inboundBalanceChanges:
          destination: balanceChangeTopic
          content-type: application/json
#          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.maxb.user: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8901/auth/user
        